name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint bloomtracker/*.py --fail-under=9.5
    - name: Check license compatibility
      run: |
        licensecheck --zero
    - name: Install package
      run: |
        pip install -e .
    - name: Test import
      run: |
        python -c "import bloomtracker; api = bloomtracker.DwdPollenApi()"
    - name: Run tests
      run: |
        python -m pytest tests/ -v
